FROM golang:1.12.5

ARG project_dir=/app/
ARG app_dir=go
WORKDIR $project_dir

RUN apt-get update && apt-get install -y mysql-client
RUN go get github.com/zenazn/goji && \
    go get github.com/zenazn/goji/web && \
    go get github.com/go-sql-driver/mysql && \
    go get github.com/gorilla/sessions 

ADD $app_dir/app.go $project_dir
ADD $app_dir/endpoint.sh $project_dir
ADD $app_dir/structure.go $project_dir
ADD $app_dir/structure.go $project_dir
ADD $app_dir/db_utility.go $project_dir

COPY $app_dir/utils/ /app/utils/
COPY ./common/ /app/common/
COPY ./public/ /app/public/

CMD ["./endpoint.sh"]

EXPOSE 5000
