# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'mysql2'
gem 'pry'
gem 'pry-byebug'
gem 'sequel'
gem 'sequel_password'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'redis'
gem 'puma'
